services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    build: ./oauth_example
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./oauth_example:/app
